"""
@ Author - Krishnabhashkar jha
@ Creation date - 7/12/2019
@ Description - Elements of Analytics Automation.
"""

# DomoPortal URL
DomoPortal_URL = 'https://basspro.domo.com'
Ten_VND_Sales = 'https://basspro.domo.com/page/134308799'
BC_SALES_DETAIL_SKU_STORE_DAY = 'https://basspro.domo.com/page/134308799/kpis/details/1857879636'
Seven_Vnd_Inventory = 'https://basspro.domo.com/page/464824174'
Bc_Total_Inventpry = 'https://basspro.domo.com/page/464824174/kpis/details/429990949'

# xpaths
Use_Direct_Sign_On = '//*[@id="login-wrapper"]/div[1]/div/div[4]/div[2]/div[2]/div/a'
Login_Email_Xpath = '//*[@id="login-wrapper"]/div[1]/div/div[4]/form/p[1]/input'
Login_Password_Xpath = '//*[@id="login-wrapper"]/div[1]/div/div[4]/form/p[2]/input'
Supplier_Login = '//*[@id="login-wrapper"]/div[1]/div/div[4]/form/div[1]'
Previous_Week = '//*[@id="cd-card-details-timeframe-label"]'
Previous_Week_Button = './/*[contains(text(),"Date Range")]//following::span/span[contains(text(),"Previous Week")]'
Previous_Week_Between = './/*[contains(text(),"Between")]'
StartDate = '//*[@id="cd-card-details-timeframe-controls"]/div/div/div[1]/div[2]/div[1]/div/input'
EndDate = '//*[@id="cd-card-details-timeframe-controls"]/div/div/div[1]/div[2]/div[2]/div/input'
Filter = "//span[@class='icon-funnel md']"
Add_Filter = '//*[@class="filter-popover-button db-button isicon"]'
Banner = './/*[contains(text(),"string")]/following::*[contains(text(),"BANNER")][1] '
BPS =".//*[contains(@id,'dim-value-')  and contains(*,'BPS')]"
CAB = ".//*[contains(@id,'dim-value-')  and contains(*,'CAB')]"
Apply = "//span[@class='button primary']"
share = './/i[contains(@class,"icon-arrow-box _24")]'
send_Export = "//div[contains(text(),'Send / Export')]"
csv_Download = '//*[@id="export-csv"]/i'
BPS_Retail = '//*[@id="0"]/div/input'
BPS_Whse = '//*[@id="1"]/div/input'
CAB_US_Retail = '//*[@id="2"]/div/input'
CAB_US_Whse = '//*[@id="3"]/div/input'
SignOutClick = '//*[@id="NotificationsPopoverToggle"]/div/div/span/div/div/img'
SignOut = '//*[@id="notificationInboxPopover"]/div[1]/div/div[3]/a[2]'



# username or Password
Columbia_Sportswear_Username = 'bassprodomo-columbia@spscommerce.com'
Columbia_Sportswear_Password = 'SPSdp123*'
Vista_Outdoors_Username = 'Christopher.Wadle@Vistaoutdoor.com'
Vista_Outdoors_Password = 'Bushne11'
Keen_Footwear_Username = 'BassProDomo-KeenOutdoor@spscommerce.com'
Keen_Footwear_Password = 'KEEN2019'
North_Face_Username = 'Dan_Meehan1@vfc.com'
North_Face_Password = 'TNF215643'
Crocs_Username = 'BassProDomo-Crocs@spscommerce.com'
Crocs_Password = 'SPSdp123*'
Beretta_Username = 'BassProDomo-Beretta@spscommerce.com'
Beretta_Password = 'BERETTA2019.'
Pure_Fishing_Username = 'jcope@purefishing.com'
Pure_Fishing_Password = 'category'
Saxx_username = 'john.macdonald@saxxunderwear.com'
Saxx_Password = 'SAXXUNDERWEAR20'
Yeti_Username = 'Jason.hamby@yeti.com'
Yeti_Password = 'Yeti2019'
Pelican_Products_Username = 'CONSUMERSALES@PELICAN.COM'
Pelican_Products_Password = 'PELPRO21'
G_Five_Outdoors_Username = 'sps.domo@g5outdoors.com'
G_Five_Outdoors_Password = 'G5analyt1c$'
LacrosseFootwear_Username = 'BassProDomo-LacrosseFootwear@spscommerce.com'
LacrosseFootwear_Password = 'SPSdp123*'
UnderArmour_Username = 'bassprodomo-underarmour@spscommerce.com'
UnderArmour_Password = 'SPSdp123**'
GerberLegendaryBlades_Username = 'SPS@gerbergear.com'
GerberLegendaryBlades_Password = 'GerberG2019'
SITKAGear_Username = 'labbott@sitkagear.com'
SITKAGear_Password = 'Sitkafall19'
Kimber_Username = 'rcleveland@kimberamerica.com'
Kimber_Password = 'RCLEVELAND'
Wolverine_Username = 'BassProDomo-Wolverine@spscommerce.com'
Wolverine_Password = 'SPSWV123*'
GearAid_Username = 'BassProDomo-GearAid@spscommerce.com'
GearAid_Password = 'SPSGEARAIDDOMO'
GildanApparel_Username = 'BassProDomo-MoretzOutdoor@spscommerce.com'
GildanApparel_Password = 'SPSdp123*'
MtnOps_Username = 'sales@mtnops.com'
MtnOps_Password = 'MTNSALES32'
VistaOutdoor_Username = 'BassProDomo-VistaOutdoor@spscommerce.com'
VistaOutdoor_Password = 'Bassprodomo1'
AmericanAccessoriesInc_Username = 'JOrr@americanaccessoriesinc.com'
AmericanAccessoriesInc_Password ='AACCESSORIESDOMO19'
BenchmadeKnifeCo_Username = 'ACalnan@benchmade.com'
BenchmadeKnifeCo_Password = 'BENCHMADEDOMO'
Chums_Username = 'scott@chums.com'
Chums_Password = 'CHUMSDOMO19'
DrewBradyCompanyInc_Username = 'dbcsales@ruia.com'
DrewBradyCompanyInc_Password = 'P4st42019'
TervisTumbler_Username = 'editechnicalcontact@tervis.com'
TervisTumbler_Password = 'TERVISDOMO2019'
BuckGardnerCalls_Username = 'domo@buckgardner.com'
BuckGardnerCalls_Password = 'BGCALLSDOMO19'
Energizer_Username = ' energizerdomo@gmail.com'
Energizer_Password = 'EHI_2019'
IndustrialRevolution_Username = 'candice@industrialrev.com'
IndustrialRevolution_Password = 'DOMOindustrev19'
Camelback_Username = 'BassProDomo-Camelback@spscommerce.com'
Camelback_Password = 'CBACKSPSDOMO19'
CarlZeiss_Username = 'barton.dobbs@zeiss.com'
Carlzeiss_Password = 'Bartond2'
Carhartt_Username = 'BassProDomo-carhartt@spscommerce.com'
Carhartt_Password = 'SPSdp123*'
AriatInternational_Username = 'SPSReporting@ariat.com'
AriatInternational_Password = 'ARIATSPSDOMO19'
HydroFlask_Username = 'brians@hydroflask.com'
HydroFlask_Password = 'HYDRODOMO19'
LifeIsGood_Username = 'rmckeown@lifeisgood.com'
LifeIsGood_Password = 'LIGGOOD22'
TenderCorp_Username = 'ccrowell@tendercorp.com'
TenderCorp_Password = 'Tender944'
LipseysInc_Username = 'luke@lipseys.com'
LipseysInc_Password = 'Syespil#1'
StrikeKingLures_Username = 'kellymudge1@gmail.com'
StrikeKingLures_Password = 'SK1DOMO20'
LewsFishingTackle_Username = 'kellym@murskibreeding.com'
LewsFishingTackle_Password = 'LF2KMUDGE'
AllianceSportsGroup_Username = 'RSmith@acgbrands.com'
AllianceSportsGroup_Password = 'ACGDOMO2019'
SmithandWesson_Username ='spsdomo@smith-wesson.com'
SmithandWesson_Password = 'SPSDOMOSW'
MarolinaOutdoorInc_Username = 'hthames@marolina.com'
MarolinaOutdoorInc_Password = 'OUTMARO33'
